/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoItem
 */
export interface TodoItem {
    /**
     * 
     * @type {number}
     * @memberof TodoItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TodoItem
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoItem
     */
    isComplete?: boolean;
}

/**
 * Check if a given object implements the TodoItem interface.
 */
export function instanceOfTodoItem(value: object): boolean {
    return true;
}

export function TodoItemFromJSON(json: any): TodoItem {
    return TodoItemFromJSONTyped(json, false);
}

export function TodoItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'isComplete': json['isComplete'] == null ? undefined : json['isComplete'],
    };
}

export function TodoItemToJSON(value?: TodoItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'isComplete': value['isComplete'],
    };
}

