/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * TodoAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface TodoItem
 */
export interface TodoItem {
    /**
     * 
     * @type {number}
     * @memberof TodoItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TodoItem
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoItem
     */
    isComplete?: boolean;
}
/**
 * TodoItemApi - fetch parameter creator
 * @export
 */
export const TodoItemApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemGet(options: any = {}): FetchArgs {
            const localVarPath = `/api/TodoItem`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemIdDelete(id: number, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiTodoItemIdDelete.');
            }
            const localVarPath = `/api/TodoItem/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemIdGet(id: number, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiTodoItemIdGet.');
            }
            const localVarPath = `/api/TodoItem/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {TodoItem} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemIdPut(id: number, body?: TodoItem, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiTodoItemIdPut.');
            }
            const localVarPath = `/api/TodoItem/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"TodoItem" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {TodoItem} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemPost(body?: TodoItem, options: any = {}): FetchArgs {
            const localVarPath = `/api/TodoItem`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"TodoItem" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TodoItemApi - functional programming interface
 * @export
 */
export const TodoItemApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemGet(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<TodoItem>> {
            const localVarFetchArgs = TodoItemApiFetchParamCreator(configuration).apiTodoItemGet(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemIdDelete(id: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = TodoItemApiFetchParamCreator(configuration).apiTodoItemIdDelete(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemIdGet(id: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<TodoItem> {
            const localVarFetchArgs = TodoItemApiFetchParamCreator(configuration).apiTodoItemIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {TodoItem} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemIdPut(id: number, body?: TodoItem, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = TodoItemApiFetchParamCreator(configuration).apiTodoItemIdPut(id, body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {TodoItem} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemPost(body?: TodoItem, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<TodoItem> {
            const localVarFetchArgs = TodoItemApiFetchParamCreator(configuration).apiTodoItemPost(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * TodoItemApi - factory interface
 * @export
 */
export const TodoItemApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemGet(options?: any) {
            return TodoItemApiFp(configuration).apiTodoItemGet(options)(fetch, basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemIdDelete(id: number, options?: any) {
            return TodoItemApiFp(configuration).apiTodoItemIdDelete(id, options)(fetch, basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemIdGet(id: number, options?: any) {
            return TodoItemApiFp(configuration).apiTodoItemIdGet(id, options)(fetch, basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {TodoItem} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemIdPut(id: number, body?: TodoItem, options?: any) {
            return TodoItemApiFp(configuration).apiTodoItemIdPut(id, body, options)(fetch, basePath);
        },
        /**
         * 
         * @param {TodoItem} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodoItemPost(body?: TodoItem, options?: any) {
            return TodoItemApiFp(configuration).apiTodoItemPost(body, options)(fetch, basePath);
        },
    };
};

/**
 * TodoItemApi - object-oriented interface
 * @export
 * @class TodoItemApi
 * @extends {BaseAPI}
 */
export class TodoItemApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoItemApi
     */
    public apiTodoItemGet(options?: any) {
        return TodoItemApiFp(this.configuration).apiTodoItemGet(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoItemApi
     */
    public apiTodoItemIdDelete(id: number, options?: any) {
        return TodoItemApiFp(this.configuration).apiTodoItemIdDelete(id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoItemApi
     */
    public apiTodoItemIdGet(id: number, options?: any) {
        return TodoItemApiFp(this.configuration).apiTodoItemIdGet(id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {number} id 
     * @param {TodoItem} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoItemApi
     */
    public apiTodoItemIdPut(id: number, body?: TodoItem, options?: any) {
        return TodoItemApiFp(this.configuration).apiTodoItemIdPut(id, body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {TodoItem} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoItemApi
     */
    public apiTodoItemPost(body?: TodoItem, options?: any) {
        return TodoItemApiFp(this.configuration).apiTodoItemPost(body, options)(this.fetch, this.basePath);
    }

}
