/**
 * TodoAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("TodoItemApi", () => {
  let instance: api.TodoItemApi
  beforeEach(function() {
    instance = new api.TodoItemApi(config)
  });

  test("apiTodoItemGet", () => {
    return expect(instance.apiTodoItemGet({})).resolves.toBe(null)
  })
  test("apiTodoItemIdDelete", () => {
    const id: number = 789
    return expect(instance.apiTodoItemIdDelete(id, {})).resolves.toBe(null)
  })
  test("apiTodoItemIdGet", () => {
    const id: number = 789
    return expect(instance.apiTodoItemIdGet(id, {})).resolves.toBe(null)
  })
  test("apiTodoItemIdPut", () => {
    const id: number = 789
    const body: api.TodoItem = undefined
    return expect(instance.apiTodoItemIdPut(id, body, {})).resolves.toBe(null)
  })
  test("apiTodoItemPost", () => {
    const body: api.TodoItem = undefined
    return expect(instance.apiTodoItemPost(body, {})).resolves.toBe(null)
  })
})

