# coding: utf-8

"""
    TodoAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import todo_api
from todo_api.models.todo_item import TodoItem  # noqa: E501
from todo_api.rest import ApiException


class TestTodoItem(unittest.TestCase):
    """TodoItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTodoItem(self):
        """Test TodoItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = todo_api.models.todo_item.TodoItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
